/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package raytw.server;

import org.junit.Test;

import raytw.server.TetrisGameServer;

import static org.junit.Assert.*;

public class TetrisGameServerTest {
    @Test public void testSomeLibraryMethod() {
        TetrisGameServer classUnderTest = new TetrisGameServer();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
