/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package raytw.server;

import java.util.concurrent.TimeUnit;
import org.apache.log4j.PropertyConfigurator;

public class TetrisGameServer {
  public boolean someLibraryMethod() {
    return true;
  }

  /**
   * Server程式進入點.
   *
   * @param args 參數
   */
  public static void main(String[] args) {
    PropertyConfigurator.configure("config//log4j.properties");
    try {
      new Thread(TetrisGameServer::startClient).start();
      KcpRttServer.main(args);
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  private static void startClient() {
    try {
      TimeUnit.SECONDS.sleep(1);
      KcpRttClient.main(null);
    } catch (Exception e) {
      e.printStackTrace();
    }
  }
}
